---
- name: Deploy Kubernetes Cluster
  hosts: all
  gather_facts: false
  become: true

  tasks:
    - name: Install Docker and Kubernetes
      include_playbook: install_kubernetes.yml

    - name: Initialize Kubernetes Cluster
      include_playbook: initialize_kubernetes.yml

    - name: Join Worker Nodes to Cluster
      include_playbook: join_cluster.yml

    - name: Configure Networking
      include_playbook: configure_network.yml
